config/routes.rb
Rails.application.routes.draw do
  get 'friends' => 'friends#show'
  get 'users/index'
  get 'users/show'
  devise_for :users
  root 'timeline#show'
  get '/home' => 'home#show'
  get 'timeline' => 'timeline#show'
  get 'notifications' => 'notifications#show'
  resources :users, only: [:show, :index]
  resources :friendship_requests, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :posts, except: [:index, :edit, :update], shallow: true do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Friendship associations
  has_many :started_friendships, foreign_key: :friendship_starter_id, class_name: 'Friendship', dependent: :destroy
  has_many :accepted_friendships, foreign_key: :friendship_accepter_id, class_name: 'Friendship', dependent: :destroy
  has_many :starter_friends, through: :accepted_friendships, source: :friendship_starter
  has_many :accepter_friends, through: :started_friendships, source: :friendship_accepter
  # Friendship Request associations
  has_many :sent_requests, foreign_key: :sender_id, class_name: 'FriendshipRequest', dependent: :destroy
  has_many :received_requests, foreign_key: :receiver_id, class_name: 'FriendshipRequest', dependent: :destroy
  has_many :friendship_request_receivers, through: :sent_requests, source: :receiver
  has_many :friendship_requesters, through: :received_requests, source: :sender
  # Posts associations
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :liker_id, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :posts
  # Comments associations
  has_many :comments, foreign_key: :author_id, dependent: :destroy

  # Validations
  validates :first_name, :last_name, presence: true,
                                     length: { maximum: 30 }



 def friends
   (starter_friends.reload + accepter_friends.reload).sort {|friend_a, friend_b| friend_a.name <=> friend_b.name}
 end

 def is_friends_with?(other_user)
   self.friends.include?(other_user)
 end

 def timeline_content
   content = self.posts.all
   friends.each do |friend|
     content += friend.posts.all
   end
   content.sort_by(&:updated_at).reverse
 end

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    # gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    # gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    # image_tag(gravatar_url, alt: user.name, class:"gravatar")
    image_tag("Icon.png", alt: user.name, class:"gravatar", height: "64px")
  end
end

app/views/users/_friend_user.html.erb
<div class="">
  <p>
    <%= link_to 'Unfriend', find_friendship(@user, current_user), method: 'delete' %>
  </p>
  <ul>
    <%= render @user.posts.ordered %>
  </ul>
</div>

app/views/users/_user.html.erb
<li class="user-list-item">
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
<h2>All Users</h2>
<ul class="list-unstyled">
  <%= render @users %>
</ul>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<ul>
  <li>
    <%= @user.email %>
  </li>
  <li>
    Other info
  </li>
</ul>

<% if current_user == @user %>
   <p>
     It's you!!
   </p>
<% elsif current_user.is_friends_with?(@user) %>
  <%= render '/users/friend_user' %>
<% elsif current_user.friendship_request_receivers.include?(@user) %>
  <div class="">
    <p>
      Friendship awaiting approval
    </p>
  </div>
<% elsif current_user.friendship_requesters.include?(@user) %>
  <div class="">
    <p>
      <%= @user.name %> wants to be your friend.
      <%= link_to 'Accept', friendships_path(
            friendship_request: FriendshipRequest.find_by(
              sender_id: @user.id,
              receiver_id: current_user.id)),
          method: 'post' %>
      <%= link_to 'Reject', friendship_request_path(
            FriendshipRequest.find_by(
              sender_id: @user.id,
              receiver_id: current_user.id)),
          method: 'delete' %>
    </p>
  </div>

<% else  %>
  <p>
    <%= link_to 'Send friendship request', friendship_requests_path(receiver_id: @user.id), method: 'post' %>
  </p>
<% end %>