config/routes.rb
Rails.application.routes.draw do
  get 'friends' => 'friends#show'
  get 'users/index'
  get 'users/show'
  devise_for :users
  root 'timeline#show'
  get '/home' => 'home#show'
  get 'timeline' => 'timeline#show'
  get 'notifications' => 'notifications#show'
  resources :users, only: [:show, :index]
  resources :friendship_requests, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :posts, except: [:index, :edit, :update], shallow: true do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_flash.html.erb
<p class="notice"><%= flash.notice %></p>
<p class="alert"><%= flash.alert %></p>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p>
    Author: Thadeu Laranja Aires
  </p>
  <p>
    This Web App was made as the final project to the Ruby on Rails course of <a href="#">The Odin Project</a>
  </p>
  <p>
    See the source at <a href="#">GitHub</a>
  </p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-items">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag("logo-280x40.png", alt: "Asgardbook Logo") %></a>
    </div>
    <div class="collapse navbar-collapse" id="nav-items">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to 'All Users', users_path %></li>
        <li><%= link_to 'Friends', friends_path %></li>
        <li><%= link_to "Notifications (#{current_user.received_requests.count})", notifications_path %></li>
        <li><%= link_to 'Timeline', timeline_path %></li>
        <li><%= link_to 'Log Out', destroy_user_session_path, method: 'delete' %></li>
      </ul>
    </div>
  </div>
</nav>