config/routes.rb
Rails.application.routes.draw do
  get 'friends' => 'friends#show'
  get 'users/index'
  get 'users/show'
  devise_for :users
  root 'timeline#show'
  get '/home' => 'home#show'
  get 'timeline' => 'timeline#show'
  get 'notifications' => 'notifications#show'
  resources :users, only: [:show, :index]
  resources :friendship_requests, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :posts, except: [:index, :edit, :update], shallow: true do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post < ActiveRecord::Base
  scope :ordered, -> { order(created_at: :desc) }
  belongs_to :author, class_name: "User"
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes
  has_many :comments, dependent: :destroy

  validates :author, presence: true
  validates :text, presence: true,
                   length: { maximum: 1000 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to home_path
    else
      render new_post_path
    end
  end

  def show
    @post = Post.find(params[:id])
    @likes = @post.likes
    @comments = @post.comments.all
    @comment = @post.comments.build
  end

  def destroy
    to_del_post = Post.find(params[:id])
    if current_user == to_del_post.author
      to_del_post.destroy
    end
    redirect_to timeline_path
  end

  private

  def post_params
    params.require(:post).permit(:text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_liked_post?
    @post.likers.include?(current_user)
  end
end

app/views/posts/_post.html.erb
<li>
  <h4><%= gravatar_for post.author %><%= link_to post.author.name, post.author %></h4>
  <p>
    <%= post.updated_at %>
  </p>
  <p>
    <%= link_to post.text, post %>
  </p>
</li>

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= form_for(@post) do |f| %>
  <%= f.label :text %><br />
  <%= f.text_area :text %>
  <%= f.submit "Submit" %>
<% end %>

app/views/posts/show.html.erb
<h2>Post Page</h2>
<p>
  <%= @post.text %>
</p>

<% unless user_liked_post? %>
  <%= link_to 'Like', post_likes_path(@post), method: 'post' %>
<% else %>
  <%= link_to 'Unlike', like_path, method: 'delete' %>
<% end %>

<% if @post.author == current_user %>
  <%= link_to 'Delete Post', post_path(@post), method: 'delete' %>
<% end %>

<h3>Comments</h3>
<ul id="comments">
  <%= render @comments %>
</ul>

<%= render 'comments/comment_form' %>

<h3><%= @likes.count %> liked this Post:</h3>
<ul id="post_likes">
  <%= render @likes %>
</ul>